# Generated by Django 3.0.6 on 2020-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newss', '0003_auto_20200609_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picurl',
            field=models.FileField(default='-', upload_to=''),
        ),
    ]
