# Generated by Django 3.0.6 on 2020-06-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newss', '0005_news_ocatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
