# Generated by Django 3.0.6 on 2020-07-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newss', '0006_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
