# Generated by Django 3.0.6 on 2020-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fb',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='insta',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='tw',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
