# Generated by Django 3.0.6 on 2020-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200605_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ph',
            field=models.CharField(default='999999', max_length=12),
        ),
    ]
