# Generated by Django 3.0.6 on 2020-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
