# Generated by Django 3.0.6 on 2020-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200620_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bodylong',
            field=models.TextField(default='-'),
        ),
    ]
